name: SpawnMob
author: jordanneil23
main: com.jordanneil23.SpawnMob.Main
version: 4_BETA
commands:
  spawnmob:
    description:
    usage: |
  smob:
    description:
    usage: |
  sm:
    description:
    usage: |
  mobspawn:
    description:
    usage: |
  mspawn:
    description:
    usage: |
  ms:
    description:
    usage: |