name: SpawnMob
softdepend: [PermissionsEX, PermissionsBukkit]
author: jordanneil23
main: com.jordanneil23.SpawnMob.Main
version: 3.2
commands:
  spawnmob:
    description:
    usage: |
  smob:
    description:
    usage: |
  sm:
    description:
    usage: |
  mspawn:
    description:
    usage: |